POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name":"James",
    "email":"James@doe.com",
    "password":"James"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email":"James@doe.com",
    "password":"James"
}

###
GET  http://localhost:5000/api/users
Authorization:  Bearer

###
GET  http://localhost:5000/api/auth/refresh_token

###
DELETE http://localhost:5000/api/auth/refresh_token
